### ISSUE TITLE
在ViewPage 里面滑动。偶先图片加载不出来！

### ISSUE THREAD

**Issue by Mixiaomi** [kareluo/AndroidPicturePreview#14]
最开始在项目里发现了这个问题，Viewpage里滑动的时候，偶尔图片加载不出来，然后在小米4上测demo。也发现了这个问题，没有什么异常抛出！有谁遇到过吗？

**Comment by Mixiaomi** [comment]
之后我一直跟代码，发现其

` public void load(ImageDecoder decoder){`
` sendMessage(MSG_IMAGE_SRC, decoder)`
`...`
`}`

Handle 没有接受到此消息

` case MSG_IMAGE_SRC:
                    prepare((ImageDecoder) msg.obj);
                    requestInvalidate();
                    break;`

导致了:`public boolean isNeedPrepare(Rect drawingRect) `

方法一直返回false;

然后在onDraw()里：

` List<ImageDrawable> drawables = mDelegate.obtainImageDrawables(mDrawingRect);
canvas.drawBitmap(drawable.mBitmap, drawable.mSrc, drawable.mDst, mPaint);`

返回的list.size = 0;图像没有绘制！

**Comment by minetsh** [comment]
看下是否这里获取到的mDrawingRect不对
``` java
@Override
protected void onDraw(Canvas canvas) {
    getDrawingRect(mDrawingRect);   
    ....
}
```

**Comment by fltwlulu** [comment]
魅族p6p上文是偶尔会有图片没加载出来，有时还闪退

**Comment by minetsh** [comment]
可以补充一些出现的crash栈日志内容 @fltwlulu

**Comment by xiaocainiaooo** [comment]
图片加载不出来的时候放大就崩溃了 
    java.lang.NullPointerException: Attempt to read from field 'int me.kareluo.intensify.image.f$b.d' on a null object reference
        at me.kareluo.intensify.image.f.c(IntensifyImageDelegate.java:306)
        at me.kareluo.intensify.image.f.a(IntensifyImageDelegate.java:499)
        at me.kareluo.intensify.image.IntensifyImageView.a(IntensifyImageView.java:196)
        at me.kareluo.intensify.image.d$b.onScale(IntensifyImageAttacher.java:36)
        at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:372)
        at me.kareluo.intensify.image.d.onTouch(IntensifyImageAttacher.java:29)
        at android.view.View.dispatchTouchEvent(View.java:12621)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)

![image](https://user-images.githubusercontent.com/11403272/48457702-91492700-e7fe-11e8-9113-085723734e97.png)

**Comment by xiaocainiaooo** [comment]
我觉得是handler 处理出问题了 
![image](https://user-images.githubusercontent.com/11403272/48457894-2cda9780-e7ff-11e8-8886-6f2f321c4371.png)
mImage 没有被创建出来

**Comment by xiaocainiaooo** [comment]
或者被回收了

**Comment by xiaocainiaooo** [comment]
解决方法
![image](https://user-images.githubusercontent.com/11403272/48528327-59f37c80-e8c9-11e8-85bb-6a0d5eb10e75.png)
![image](https://user-images.githubusercontent.com/11403272/48528334-6081f400-e8c9-11e8-83ec-410836d49f16.png)

**Comment by xiaocainiaooo** [comment]
解决手机 magic2 系统magic 2.0 （基于emui9.0）
