### ISSUE TITLE
报空指针

### ISSUE THREAD

**Issue by wangshouxue** [kareluo/AndroidPicturePreview#17]
java.lang.NullPointerException: Attempt to read from field 'int me.kareluo.intensify.image.IntensifyImageDelegate$c.d' on a null object reference
    at me.kareluo.intensify.image.IntensifyImageDelegate.h(TbsSdkJava:2)
    at me.kareluo.intensify.image.IntensifyImageDelegate.r(TbsSdkJava:1)
    at me.kareluo.intensify.image.IntensifyImageDelegate.f(TbsSdkJava:1)
    at me.kareluo.intensify.image.IntensifyImageDelegate$j.onAnimationUpdate(TbsSdkJava:3)
    at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
    at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
    at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
    at android.view.Choreographer.doCallbacks(Choreographer.java:875)
    at android.view.Choreographer.doFrame(Choreographer.java:772)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
    at android.os.Handler.handleCallback(Handler.java:888)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8147)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by AaronOhO** [comment]
这个有稳定复现的场景么？
