### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by chztp** [kareluo/AndroidPicturePreview#2]
出现OOM问题

**Comment by minetsh** [comment]
请详细描述一下出现的过程

**Comment by chztp** [comment]
用viewPager来左右滑动图片，在PagerAdapter中创建IntensifyImageView对象，并通过传入图片路径显示图片，在滑动的过程中会偶发性出现OOM现象，图片量比较大有几千张

**Comment by huyulin** [comment]
楼主好，我是一张8000x4500的。方法了滑，滑到一定距离之后就蹦了。

**Comment by huyulin** [comment]
TIME=1460716576000
FINGERPRINT=rockchip/rk3188/rk3188:4.4.4/KTU84Q/eng.alvin.20160415.183536:eng/test-keys
HARDWARE=rk30board
UNKNOWN=unknown
RADIO=unknown
BOARD=rk30sdk
versionCode=1
PRODUCT=rk3188
versionName=1.0
USE_LCDC_COMPOSER=false
DISPLAY=rk3188-eng 4.4.4 KTU84Q eng.alvin.20160415.183536 test-keys
USER=alvin
HOST=ubuntu-zysj
DEVICE=rk3188
TAGS=test-keys
MODEL=rk3188
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=true
ID=KTU84Q
SERIAL=RXZ2P5YAMG
MANUFACTURER=rockchip
BRAND=rockchip
TYPE=eng
java.lang.OutOfMemoryError
    at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
    at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
    at me.kareluo.intensify.image.IntensifyImageCache$ImageCache.create(IntensifyImageCache.java:76)
    at me.kareluo.intensify.image.IntensifyImageCache$ImageCache.create(IntensifyImageCache.java:42)
    at me.kareluo.intensify.image.IntensifyCache.createGet(IntensifyCache.java:152)
    at me.kareluo.intensify.image.IntensifyImageDelegate.prepareDraw(IntensifyImageDelegate.java:254)
    at me.kareluo.intensify.image.IntensifyImageDelegate.access$1000(IntensifyImageDelegate.java:34)
    at me.kareluo.intensify.image.IntensifyImageDelegate$IntensifyImageHandler.handleMessage(IntensifyImageDelegate.java:741)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)
