### ISSUE TITLE
IntensifyImageView在RecyclerView 和ListView中无法显示啊

### ISSUE THREAD

**Issue by gitHubVoid** [kareluo/AndroidPicturePreview#9]

**Comment by gitHubVoid** [comment]
FATAL EXCEPTION: IntensifyImageDelegate
                                                                              Process: me.kareluo.intensify.preview, PID: 13239
                                                                              java.lang.NullPointerException: Attempt to read from field 'int me.kareluo.intensify.image.IntensifyImageDelegate$Image.mImageWidth' on a null object reference
                                                                                  at me.kareluo.intensify.image.IntensifyImageDelegate.initialize(IntensifyImageDelegate.java:146)
                                                                                  at me.kareluo.intensify.image.IntensifyImageDelegate.access$1400(IntensifyImageDelegate.java:34)
                                                                                  at me.kareluo.intensify.image.IntensifyImageDelegate$IntensifyImageHandler.handleMessage(IntensifyImageDelegate.java:762)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by minetsh** [comment]
RecyclerView和ListView不需要显示很大的图片吧，这个库主要是大图预览，不应该嵌套在他们中

**Comment by gitHubVoid** [comment]
你看看新浪微博的话题详情 他们是把长图大图嵌套到里面了
